tilesdir: /run/media/jer/ARCHIVE/HIMAWARI_DATA/tiles
tmp: /run/media/jer/ARCHIVE/HIMAWARI_DATA/tmp
completed: /run/media/jer/ARCHIVE/HIMAWARI_DATA/completed
backup: /run/media/jer/ARCHIVE/HIMAWARI_DATA/tmp
